template:
  path: tower-project.j2
stack_name: genie-bpc-project

dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml

parameters:
  S3ReadWriteAccessArns:
    - '{{stack_group_config.tower_viewer_arn_prefix}}/xindi.guo@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/chelsea.nayan@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/rixing.xu@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/dan.lu@sagebase.org'
    - '{{stack_group_config.tower_viewer_arn_prefix}}/adam.taylor@sagebase.org'
  AllowSynapseIndexing: Enabled
  AccountAdminArns:
    - '{{stack_group_config.sso_admin_role.arn}}'
    - !stack_output_external sagebase-github-oidc-workflows-prod-nextflow-infra::ProviderRoleArn
  TemplateRootUrl: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com'
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

stack_tags:
  Department: SCCE
  Project: GENIE
  OwnerEmail: thomas.yu@sagebase.org
  CostCenter: Genie-AACR BPC / 312100
